### ISSUE TITLE
Code Assignment 7.4.1.3 autograder issue

### ISSUE THREAD

**Issue by MrMazzone** [bhoffman0/CSAwesome#52]
Hi Beryl, 

One of the Coding Rooms users noticed that a test case was not fulling passing even though it showed two individual tests that both passed.
![image](https://user-images.githubusercontent.com/40954645/153669750-ccf420af-c3e1-4c57-a76d-ae1727888b76.png)

The issue seemed to be related to the main method test not working properly.
```
@Test
   public void testMain() throws IOException
   {
     String output = getMethodOutput("main");
     String expect = "[TNA, BARCADABARA, PAPLE]";
     boolean passed = output.contains(expect);
     assertTrue(passed);
     System.out.println("expected output from main");
   }
```

Upon investigation, we noticed Runestone has the same issue. 
![image](https://user-images.githubusercontent.com/40954645/153669636-97e6e84f-bbdf-44e7-933b-3ffed3c41eb1.png)

**Comment by bhoffman0** [comment]
Thanks I think I've fixed it with the test below. Not sure how the println got in there, but it would probably mess up things. It should be live tomorrow.
@Test
      public void testMain() throws IOException
      {
        String output = getMethodOutput("main");
        String expect = "[TNA, BARCADABARA, PAPLE]";
        boolean passed = output.contains(expect);
        passed = getResults(expect, output, "expected output from main", passed);
        assertTrue(passed);
      }

**Comment by MrMazzone** [comment]
FYI, Beryl.  That seemed to fix everything on our end. Thank you!
