### ISSUE TITLE
1.5.2 Summary Issue

### ISSUE THREAD

**Issue by RichardatCodingRooms** [bhoffman0/CSAwesome#60]
Hello there!

Richard here from the Coding Rooms team. Hope you're doing well. One of our users mentioned an issue in the content here, where an emdash looks to have replaced what should be --.

https://runestone.academy/ns/books/published/csawesome/Unit1-Getting-Started/topic-1-5-shortcutoperators.html#summary
![image](https://user-images.githubusercontent.com/92591980/213547493-d7944d49-2cf6-4b39-bbac-9aa65f690eb2.png)

**Comment by bhoffman0** [comment]
Thanks! Fixed.
