### ISSUE TITLE
Typo in 1.7.2

### ISSUE THREAD

**Issue by RichardatCodingRooms** [bhoffman0/CSAwesome#61]
Hello! Here's another one raised by the same user that reported the last one:

![image](https://user-images.githubusercontent.com/92591980/214049845-1e5ce94a-cfad-46dd-a72a-fdbd9ad66af6.png)

https://runestone.academy/ns/books/published/csawesome/Unit1-Getting-Started/topic-1-7-summary.html?mode=browsing#java-keyword-summary

**Comment by bhoffman0** [comment]
Fixed thanks. Will be live soon.
