### ISSUE TITLE
CSA 12.2, Exam 2, Question 13

### ISSUE THREAD

**Issue by RichardatCodingRooms** [bhoffman0/CSAwesome#65]
A Coding Rooms user reported an issue in the 12-2-13 question which appears to be present on Runestone around the 12th line:
![image](https://user-images.githubusercontent.com/92591980/233677197-3dbab753-cfb8-4904-b803-da55b7a34116.png)

>AP Practice test 12.2 Exam 1 Question 13
Inner for loop should not have println

**Comment by bhoffman0** [comment]
Sorry forgot about this. It will be fixed.
